[tool.ruff]
line-length = 88
select = ["E", "F"]
exclude = [
  ".git",
  ".ruff_cache",
  "__pycache__",
  "build",
  "data",
  "node_modules",
  "venv",
]
ignore = [
  "E402",
]

[tool.black]
line-length = 88
target-version = ['py310']

[tool.pytest.ini_options]
addopts = "-n auto --mypy -v --cov-report html:cov_html --cov-report annotate:cov_annotate --junitxml=test-results/pytest/results.xml --cov-report term-missing:skip-covered --cov ."
norecursedirs = [
  ".git",
  "__pycache__",
  "data",
  "node_modules",
  "venv",
]

[tool.isort]
profile = "open_stack"

[tool.mypy]
python_version = "3.10"

[[tool.mypy.overrides]]
module = [
  "PIL",
  "PIL.Image",
  "assertpy",
  "bitstring",
  "matplotlib",
  "matplotlib.dates",
  "matplotlib.patches",
  "matplotlib.pyplot",
  "mypy-numpy",
  "networkx",
  "ortools.linear_solver",
  "pysat.solvers",
  "pytest",
  "scipy.linalg",
  "scipy.spatial.distance",
  "shapely",
  "shapely.affinity",
]
ignore_missing_imports = true

[tool.coverage.run]
omit = [
  "*_test.py",
  "*site-packages*",
  "__pycache__/*",
  "venv/*",
]

[tool.coverage.report]
exclude_lines = [
  "@abc.abstractmethod",
  "@abstractmethod",
  "def __repr__",
  "if __name__ == .__main__.:",
  "pass",
  "pragma: no cover",
  "raise NotImplementedError",
]
