version: 2.1

orbs:
  python: circleci/python@1.4.0

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10.6
    # https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: large
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Test and upload coverage
          command: |
              cp -f .circleci/resources/circleci_setup.cfg setup.cfg
              python -m pytest
              python -m coveralls
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  main:
    jobs:
      - build_and_test
